model_path: "weights/yolov8s-seg.pt"
classes: []  # list for class labels e.g.('shiba')
colors: {}   # dict for class label colors e.g.{'shiba': (255, 0, 0)}
log: false
display: true
max_model_size: 640
det_conf: 0.5
iou: 0.6
