model_path: "weights/slideS2-1-tune23.pt"
classes: ['handle', 'stair']  # list for class labels e.g.('shiba')
colors: 
  handle: [255, 0, 0]
  stair: [0, 200, 0]
log: false
display: true
max_model_size: 640
det_conf: 0.45
iou: 0.6
